[package]
name = "spectrbar"
version = "1.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
battery = "0.7.8"
dbus = "0.9.7"
maildir = "0.6.4"
debug_print = "1.0.0"
